import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

export const countries = [
  { code: 'US', name: 'English', lang: 'en', flag: '🇺🇸' },
  { code: 'RU', name: 'Русский', lang: 'ru', flag: '🇷🇺' },
  { code: 'UA', name: 'Українська', lang: 'uk', flag: '🇺🇦' },
]

export const translations = {
  en: {
    // Header
    signIn: 'Sign In',
    signOut: 'Sign Out',
    signInRequired: 'Sign In Required',
    signInToAccessWallet: 'Please sign in to access your wallet',
    
    // Home
    tagline: 'Global marketplace for beats',
    exploreBeats: 'Explore Beats',
    uploadBeat: 'Upload Beat',
    buyBeat: 'Buy Beat',
    sellBeat: 'Sell Beat',
    
    // Explore
    explore: 'Explore',
    beats: 'beats',
    searchPlaceholder: 'Search beats or producers...',
    genre: 'Genre',
    mood: 'Mood',
    bpm: 'BPM',
    price: 'Price',
    all: 'All',
    noBeatsFound: 'No beats found',
    buy: 'Buy',
    
    // Beat Page
    back: 'Back',
    selectLicense: 'Select License',
    secureCheckout: 'Secure checkout • Instant download',
    plays: 'plays',
    by: 'by',
    
    // Auth
    welcomeBack: 'Welcome back',
    signInToAccount: 'Sign in to your account',
    createAccount: 'Create account',
    startSelling: 'Start selling beats worldwide',
    email: 'Email',
    password: 'Password',
    producerName: 'Producer name',
    forgotPassword: 'Forgot password?',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    signUp: 'Sign up',
    resetPassword: 'Reset password',
    enterEmailReset: 'Enter your email to receive a reset link',
    sendResetLink: 'Send Reset Link',
    continueWithGoogle: 'Continue with Google',
    termsAgree: 'By creating an account, you agree to our',
    termsOfService: 'Terms of Service',
    and: 'and',
    privacyPolicy: 'Privacy Policy',
    or: 'or',
    
    // Email verification
    verifyEmailFirst: 'Please verify your email first. Check your inbox.',
    verificationSent: 'Verification email sent! Please check your inbox.',
    verificationResent: 'Verification email resent!',
    checkYourEmail: 'Check your email',
    verificationSentTo: 'We sent a verification link to',
    clickLinkToVerify: 'Click the link in the email to verify your account.',
    checkSpamFolder: 'If you don\'t see our email, please check your Spam folder.',
    resendEmail: 'Resend Email',
    backToSignIn: 'Back to Sign In',
    passwordMinLength: 'Password must be at least 6 characters',
    waitingForVerification: 'Waiting for verification...',
    emailVerified: 'Email verified successfully!',
    emailVerifiedTitle: 'You\'re verified!',
    emailVerifiedMessage: 'Your email has been confirmed. Welcome to 808!',
    redirecting: 'Redirecting...',
    
    // Upload validation
    audioFileRequired: 'Please upload an audio file to publish your beat',
    
    // Profile
    uploadedBeats: 'Uploaded Beats',
    salesHistory: 'Sales History',
    totalSales: 'Total Sales',
    revenue: 'Revenue',
    totalPlays: 'Total Plays',
    followers: 'followers',
    
    // Wallet
    wallet: 'Wallet',
    myWallet: 'My Wallet',
    availableBalance: 'Available Balance',
    holdBalance: 'Hold Balance',
    holdNote: 'Funds are held for 48 hours after sale',
    pending: 'Pending',
    clearsIn: 'Clears in 7 days',
    withdraw: 'Withdraw',
    topUp: 'Top Up',
    topUpBalance: 'Top Up Balance',
    paymentMethods: 'Payment Methods',
    addMethod: 'Add Method',
    transactionHistory: 'Transaction History',
    noTransactions: 'No transactions yet',
    fundsReleased: 'Funds Released',
    connectWallet: 'Connect Wallet',
    cryptoComingSoon: 'Crypto (Coming Soon)',
    comingSoon: 'Coming Soon',
    paymentMethodsComingSoon: 'Top-up and withdrawal methods will be available soon',
    withdrawFunds: 'Withdraw Funds',
    amount: 'Amount',
    available: 'Available',
    withdrawTo: 'Withdraw to',
    cancel: 'Cancel',
    soldTo: 'Sold to',
    withdrawal: 'Withdrawal',
    
    // Purchases
    myPurchases: 'My Purchases',
    noPurchases: 'No purchases yet',
    startBuying: 'Start buying beats from talented producers',
    purchased: 'Purchased',
    license: 'License',
    downloadBeat: 'Download Beat',
    download: 'Download',
    licenseOwned: 'You own this license',
    downloadNow: 'Download Now',
    onHold: 'On Hold',
    completed: 'Completed',
    cancelled: 'Cancelled',
    disputed: 'Disputed',
    pendingConfirmation: 'Pending confirmation',
    sellerCheckingPayment: 'Seller is checking payment...',
    noRefundTitle: 'No refund available',
    noRefundDesc: 'You can dispute this order. If you have proof, admin can manually deliver the beat.',
    disputeButton: 'Dispute',
    disputeUnderReview: 'Dispute under review',
    reportProblem: 'Report a Problem',
    describeIssue: 'Describe the issue with this purchase',
    disputeReasonPlaceholder: 'Explain what went wrong...',
    submitDispute: 'Submit Dispute',
    
    // Buy
    buyFor: 'Buy for',
    yourBalance: 'Your balance',
    insufficientFunds: 'Insufficient Funds',
    needMore: 'You need',
    toComplete: 'more to complete this purchase',
    topUpWallet: 'Top Up Wallet',
    purchaseSuccess: 'Purchase Successful!',
    beatNowYours: 'The beat is now yours. You can download it anytime.',
    close: 'Close',
    ownBeat: 'This is your beat',
    
    // Manual Purchase System
    contactToBuy: 'Contact to Buy',
    directPayment: 'Direct payment to seller • Manual verification',
    digitalGoodsNotice: 'Digital goods • No refunds after delivery',
    purchaseBeat: 'Purchase Beat',
    review: 'Review',
    payment: 'Payment',
    proof: 'Proof',
    deliveryTime: 'Delivery Time',
    deliveryTimeDesc: 'Within 10 minutes after payment confirmation',
    manualVerification: 'Manual Verification',
    manualVerificationDesc: 'Seller verifies payment before delivery',
    noRefunds: 'No Refunds',
    noRefundsDesc: 'Digital goods are non-refundable after delivery',
    purchaseTerms: 'Purchase Terms',
    term1: 'Payments are made directly to the seller',
    term2: 'The platform does not process or store payments',
    term3: 'Digital goods are delivered after payment confirmation',
    term4: 'All sales are final due to the digital nature of the product',
    continueToPayment: 'Continue to Payment',
    paymentInstructions: 'Payment Instructions',
    paymentInstructionsDesc: 'Send payment using one of the methods below',
    amountToPay: 'Amount to Pay',
    contactSeller: 'Contact Seller',
    contactSellerDesc: 'Contact the seller directly to get payment details',
    important: 'Important',
    includeOrderRef: 'Include this reference in your payment message:',
    iHavePaid: "I've Made Payment",
    submitPaymentProof: 'Submit Payment Proof',
    submitPaymentProofDesc: 'Upload a screenshot of your payment confirmation',
    uploadScreenshot: 'Click to upload screenshot',
    maxFileSize: 'Max file size: 10MB',
    transactionId: 'Transaction ID / Reference',
    transactionIdPlaceholder: 'Enter transaction ID or reference number',
    yourEmail: 'Your Email',
    emailPlaceholder: 'Enter your email address',
    emailNote: "We'll send the beat to this email after confirmation",
    submitting: 'Submitting...',
    submitOrder: 'Submit Order',
    orderSubmitted: 'Order Submitted!',
    orderSubmittedDesc: 'Your order is being reviewed by the seller',
    orderReference: 'Order Reference',
    pendingVerification: 'Pending Verification',
    whatHappensNext: 'What happens next?',
    nextStep1: 'The seller will verify your payment',
    nextStep2: "Once confirmed, you'll receive the beat via email",
    nextStep3: 'Delivery usually takes up to 10 minutes',
    checkEmail: 'Check your email for order updates',
    done: 'Done',
    
    // Orders (Seller)
    orders: 'Orders',
    incomingOrders: 'Incoming Orders',
    manageYourOrders: 'Manage orders from buyers',
    totalOrders: 'Total',
    signInToViewOrders: 'Please sign in to view your orders',
    noOrders: 'No Orders',
    noOrdersDesc: "You don't have any orders yet",
    buyerInfo: 'Buyer Information',
    name: 'Name',
    orderRef: 'Order Ref',
    date: 'Date',
    paymentProof: 'Payment Proof',
    viewFull: 'View Full Size',
    noProofUploaded: 'No proof uploaded',
    approvePayment: 'Approve Payment',
    rejectOrder: 'Reject',
    enterRejectReason: 'Enter reason for rejection:',
    readyToDeliver: 'Ready to Deliver',
    sendBeatToEmail: "Send the beat file to the buyer's email address",
    sendEmail: 'Open Email',
    markDelivered: 'Mark as Delivered',
    rejectionReason: 'Rejection Reason',
    orderDelivered: 'This order has been delivered',
    approved: 'Approved',
    rejected: 'Rejected',
    delivered: 'Delivered',
    status: 'Status',
    
    // Seller Sales Tab
    pendingReview: 'Pending review',
    viewPaymentProof: 'View proof',
    moneyReceived: 'Money received',
    moneyNotReceived: 'Money not received',
    dealCompleted: 'Deal completed',
    cancelledBuyerCanDispute: 'Cancelled • Buyer can dispute',
    
    // Dispute System
    disputeOrder: 'Dispute',
    enterDisputeReason: 'Enter reason for dispute (explain why you believe the payment is invalid):',
    disputeSubmitted: 'Dispute submitted. An administrator will review this case.',
    errorCreatingDispute: 'Failed to create dispute',
    underAdminReview: 'Under Admin Review',
    disputeReason: 'Dispute Reason',
    adminWillReview: 'An administrator will review this case and make a final decision.',
    adminDeliveredOrder: 'Admin Delivered',
    adminDeliveredDesc: 'This order was delivered by an administrator after reviewing the dispute.',
    adminNotes: 'Admin Notes',
    adminDelivered: 'Admin Delivered',
    paymentDate: 'Payment Date',
    paymentTime: 'Payment Time',
    cardLastFour: 'Card Last 4 Digits',
    cardLastFourPlaceholder: 'Last 4 digits of your card',
    actionHistory: 'Action History',
    
    // Admin Arbitration
    orderArbitration: 'Order Arbitration',
    sellerInfo: 'Seller Information',
    sellerId: 'Seller ID',
    beatId: 'Beat ID',
    disputedBy: 'Disputed by',
    adminActions: 'Admin Actions',
    forceDeliver: 'Force Deliver to Buyer',
    approveOrder: 'Approve Order',
    enterAdminNotes: 'Enter admin notes explaining your decision:',
    adminActionNote: 'All admin actions are logged and visible to both buyer and seller.',
    
    // Purchase Modal - Admin Protection
    adminProtection: 'Admin Protection',
    adminProtectionDesc: 'If the seller fails to deliver after valid payment, an administrator can override and deliver the product to you.',
    legalTitle: 'Important Legal Notice',
    legal1: 'This platform does not process, store, or handle any payments.',
    legal2: 'All transactions occur directly between buyer and seller.',
    legal3: 'The platform only facilitates proof verification and delivery.',
    legal4: 'By proceeding, you acknowledge this is a direct peer-to-peer transaction.',
    legal5: 'In case of disputes, admin will review proof and make a final decision.',
    
    // Stripe Wallet
    paymentSuccessful: 'Payment successful! Your balance has been updated.',
    paymentCanceled: 'Payment was canceled.',
    paymentError: 'Failed to process payment. Please try again.',
    selectAmount: 'Select an amount to add to your wallet',
    customAmount: 'Custom Amount',
    amountRange: 'Min: $1 • Max: $1,000',
    invalidAmount: 'Amount must be between $5 and $1,000',
    creditDebitCard: 'Credit / Debit Card',
    securePayment: 'Secured by Stripe. We never store your card details.',
    payAmount: 'Pay',
    processing: 'Processing...',
    failed: 'Failed',
    expired: 'Expired',
    refund: 'Refund',
    withdrawError: 'Failed to process withdrawal',
    
    // Sales
    sales: 'Sales',
    salesCount: 'sales',
    noSalesYet: 'No sales yet',
    uploadBeatsToSell: 'Upload beats to start selling',
    
    // Upload
    uploadBeatTitle: 'Upload Beat',
    licenseFiles: 'License Files',
    selectLicensesToSell: 'Select which licenses you want to sell. Click checkbox to enable license.',
    uploadFilesForEachLicense: 'Upload separate files for each license type',
    selectMp3: 'Select MP3 file',
    selectWav: 'Select WAV file',
    selectStems: 'Select Stems (ZIP)',
    selectExclusive: 'Select Exclusive file',
    mp3FileRequired: 'MP3 file is required',
    wavFileRequired: 'WAV file is required (license enabled)',
    trackoutFileRequired: 'Trackout file is required (license enabled)',
    exclusiveFileRequired: 'Exclusive file is required (license enabled)',
    clickToEnable: 'Click checkbox to enable',
    onlyMp3Allowed: 'Only MP3 files allowed',
    onlyWavAllowed: 'Only WAV files allowed',
    onlyZipAllowed: 'Only ZIP/RAR files allowed',
    onlyZipWavAllowed: 'Only ZIP, RAR or WAV files allowed',
    uploadingMp3: 'Uploading MP3...',
    uploadingWav: 'Uploading WAV...',
    uploadingTrackout: 'Uploading Trackout...',
    uploadingExclusive: 'Uploading Exclusive...',
    audioFile: 'Audio File',
    dragDrop: 'Drag and drop your beat here, or',
    browse: 'browse',
    fileTypes: 'MP3, WAV, FLAC up to 100MB',
    uploadingAudio: 'Uploading audio...',
    uploadingCover: 'Uploading cover...',
    savingBeat: 'Saving beat...',
    coverImage: 'Cover Image',
    addCover: 'Add cover image',
    optional: 'optional',
    coverLinkHint: 'Paste link to cover image (imgur, imgbb, etc.) - optional',
    titleRequired: 'Title is required',
    beatInfo: 'Beat Information',
    title: 'Title',
    beatName: 'Beat name',
    selectGenre: 'Select genre',
    selectKey: 'Select key',
    selectMood: 'Select mood',
    pricing: 'Pricing',
    publishBeat: 'Publish Beat',
    howToUpload: 'How to upload?',
    recommended: 'recommended',
    driveStep1: 'Upload your beat to Google Drive',
    driveStep2: 'Right-click the file → Share',
    driveStep3: 'Set access to "Anyone with the link"',
    driveStep4: 'Copy link and paste here',
    dropboxStep1: 'Upload to Dropbox and get sharing link',
    dropboxStep2: 'Paste the link here',
    willPlayOnSite: 'will play directly on site',
    mayNotPlay: 'may not play directly, link only',
    unknownPlatform: 'Unknown platform',
    
    // Genres
    trap: 'Trap',
    drill: 'Drill',
    rnb: 'R&B',
    hiphop: 'Hip-Hop',
    pop: 'Pop',
    lofi: 'Lo-Fi',
    
    // Moods
    dark: 'Dark',
    chill: 'Chill',
    aggressive: 'Aggressive',
    energetic: 'Energetic',
    sad: 'Sad',
    happy: 'Happy',
    
    // Licenses
    mp3Lease: 'MP3 Lease',
    wavLease: 'WAV Lease',
    trackout: 'Trackout',
    exclusive: 'Exclusive',

    // Country selector
    selectCountry: 'Select Country',

    // Settings
    settings: 'Settings',
    clickToChangeAvatar: 'Click to change avatar',
    canChangeNameIn: 'You can change your name in',
    days: 'days',
    saveChanges: 'Save Changes',
    settingsSaved: 'Settings saved successfully',
    dangerZone: 'Danger Zone',
    
    // Profile
    myBeats: 'My Beats',
    liked: 'Liked',
    purchases: 'Purchases',
    noBeatsYet: 'No beats yet',
    uploadFirstBeat: 'Upload your first beat to start selling',
    noLikedBeats: 'No liked beats yet',
    exploreLikeBeats: 'Explore beats and like your favorites',
    exploreToBuy: 'Explore beats and buy your favorites',
    from: 'from',
    exploreCatalog: 'Explore Catalog',
    editBeat: 'Edit Beat',
    delete: 'Delete',
    deleteBeatConfirm: 'Delete this beat?',
    deleteBeatWarning: 'This action cannot be undone. The beat will be permanently removed.',

    // Terms page
    termsTitle: '808 — Terms of Service',
    privacyTitle: 'Privacy Policy',
    licensingTitle: 'Beat Licensing Agreement',
    effectiveDate: 'Effective Date: January 27, 2026',
    termsIntro: 'These Terms of Service ("Terms") govern your access to and use of the 808 platform ("808", "we", "us", or "our").',
    termsAgreeIntro: 'By creating an account or using the platform, you agree to these Terms.',
    
    eligibilityTitle: '1. Eligibility',
    eligibilityText: 'You must be at least 18 years old to use 808. By using the platform, you confirm that you meet this requirement.',
    
    accountsTitle: '2. Accounts',
    accountsSecurity: 'You are responsible for maintaining the security of your account',
    accountsActivity: 'All activity under your account is your responsibility',
    accountsAccurate: 'You must provide accurate and up-to-date information',
    
    platformTitle: '3. Platform Description',
    platformText: '808 is a global digital marketplace that allows producers to upload, license, and sell music beats, and allows customers to purchase licenses to those beats.',
    
    ownershipTitle: '4. Content Ownership',
    ownershipRetain: 'Producers retain full ownership of their uploaded beats',
    ownershipConfirm: 'By uploading content, you confirm that you own or control all necessary rights',
    ownershipNoClaim: '808 does not claim ownership of user content',
    ownershipGrant: 'You grant 808 a non-exclusive, worldwide, royalty-free license to host, stream, display, and promote your content solely for operating the platform',
    
    copyrightTitle: '5. Copyright & DMCA',
    copyrightRespect: '808 respects intellectual property rights.',
    copyrightNotice: 'If you believe that copyrighted material has been uploaded without authorization, please submit a DMCA notice to',
    copyrightViolation: 'Repeated copyright violations may result in account termination.',
    
    licensesTitle: '6. Licenses & Purchases',
    licensesGrant: 'Purchasing a beat grants a license, not ownership',
    licensesDefined: "License terms are defined on each beat's page",
    licensesBinding: 'Licenses are binding upon purchase',
    licensesFinal: 'All sales are final unless otherwise required by law',
    
    paymentsTitle: '7. Payments & Fees',
    paymentsProcessed: 'Payments are processed via third-party providers (e.g. Stripe, PayPal)',
    paymentsFee: '808 may charge a platform service fee',
    paymentsTax: 'You are responsible for all applicable taxes',
    paymentsErrors: '808 is not responsible for payment provider errors or delays',
    
    prohibitedTitle: '8. Prohibited Use',
    prohibitedIntro: 'You may not:',
    prohibitedStolen: 'Upload stolen or infringing content',
    prohibitedIllegal: 'Use the platform for illegal activities',
    prohibitedExploit: 'Attempt to exploit, reverse-engineer, or harm the platform',
    
    terminationTitle: '9. Termination',
    terminationText: '808 reserves the right to suspend or terminate accounts that violate these Terms or applicable laws.',
    
    disclaimerTitle: '10. Disclaimer',
    disclaimerText: 'The platform is provided "as is" without warranties of any kind. 808 does not provide legal advice and is not responsible for disputes between buyers and sellers.',
    
    liabilityTitle: '11. Limitation of Liability',
    liabilityText: 'To the maximum extent permitted by law, 808 shall not be liable for indirect, incidental, or consequential damages, including lost profits or data.',
    
    governingTitle: '12. Governing Law',
    governingText: 'These Terms are governed by and construed in accordance with applicable international laws.',
    
    changesTitle: '13. Changes',
    changesText: 'We may update these Terms at any time. Continued use of the platform constitutes acceptance of the updated Terms.',
    
    // Privacy
    dataCollectTitle: '1. Data We Collect',
    dataAccount: 'Account information (email, username)',
    dataPayment: 'Payment-related data (processed by third parties)',
    dataUsage: 'Usage and analytics data',
    
    dataUseTitle: '2. How We Use Data',
    dataOperate: 'To operate and improve the platform',
    dataProcess: 'To process transactions',
    dataCommunicate: 'To communicate important updates',
    
    dataSharingTitle: '3. Data Sharing',
    dataSharingText: 'We do not sell personal data. Data is shared only with trusted service providers when necessary.',
    
    legalComplianceTitle: '4. Legal Compliance',
    legalComplianceText: 'We process personal data in accordance with applicable data protection laws, including GDPR and CCPA, where applicable.',
    
    securityTitle: '5. Security',
    securityText: 'We apply industry-standard security measures to protect your information.',
    
    yourRightsTitle: '6. Your Rights',
    yourRightsText: 'You may request access, correction, or deletion of your personal data at any time by contacting',
    
    // Licensing
    licensingIntro: 'This Licensing Agreement applies to all beat purchases made on 808.',
    
    licenseGrantTitle: '1. License Grant',
    licenseGrantText: 'Upon purchase, the buyer is granted a non-exclusive or exclusive license as specified on the beat page.',
    
    restrictionsTitle: '2. Restrictions',
    restrictionsIntro: 'Unless explicitly stated, the buyer may not:',
    restrictionsClaim: 'Claim ownership of the beat',
    restrictionsResell: 'Resell or sublicense the beat',
    restrictionsRegister: 'Register the beat as their own with copyright agencies',
    
    creditTitle: '3. Credit',
    creditText: 'Where required by the license, proper credit must be given to the producer.',
    
    licenseTerminationTitle: '4. Termination',
    licenseTerminationText: 'Violation of license terms may result in license termination without refund.',
    
    agreementNotice: 'By creating an account, you agree to the Terms of Service, Privacy Policy, and Licensing Agreement of 808.',
  },
  
  ru: {
    // Header
    signIn: 'Войти',
    signOut: 'Выйти',
    signInRequired: 'Требуется вход',
    signInToAccessWallet: 'Войдите, чтобы получить доступ к кошельку',
    
    // Home
    tagline: 'Глобальный маркетплейс битов',
    exploreBeats: 'Смотреть биты',
    uploadBeat: 'Загрузить бит',
    buyBeat: 'Купить бит',
    sellBeat: 'Продать бит',
    
    // Explore
    explore: 'Каталог',
    beats: 'битов',
    searchPlaceholder: 'Поиск битов или продюсеров...',
    genre: 'Жанр',
    mood: 'Настроение',
    bpm: 'BPM',
    price: 'Цена',
    all: 'Все',
    noBeatsFound: 'Биты не найдены',
    buy: 'Купить',
    
    // Beat Page
    back: 'Назад',
    selectLicense: 'Выберите лицензию',
    secureCheckout: 'Безопасная оплата • Мгновенная загрузка',
    plays: 'прослушиваний',
    by: 'от',
    
    // Auth
    welcomeBack: 'С возвращением',
    signInToAccount: 'Войдите в аккаунт',
    createAccount: 'Создать аккаунт',
    startSelling: 'Начните продавать биты по всему миру',
    email: 'Email',
    password: 'Пароль',
    producerName: 'Имя продюсера',
    forgotPassword: 'Забыли пароль?',
    dontHaveAccount: 'Нет аккаунта?',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    signUp: 'Регистрация',
    resetPassword: 'Сброс пароля',
    enterEmailReset: 'Введите email для получения ссылки',
    sendResetLink: 'Отправить ссылку',
    continueWithGoogle: 'Продолжить с Google',
    termsAgree: 'Создавая аккаунт, вы соглашаетесь с',
    termsOfService: 'Условиями использования',
    and: 'и',
    privacyPolicy: 'Политикой конфиденциальности',
    or: 'или',
    
    // Email verification
    verifyEmailFirst: 'Сначала подтвердите email. Проверьте почту.',
    verificationSent: 'Письмо отправлено! Проверьте почту.',
    verificationResent: 'Письмо отправлено повторно!',
    checkYourEmail: 'Проверьте почту',
    verificationSentTo: 'Мы отправили ссылку на',
    clickLinkToVerify: 'Нажмите на ссылку в письме чтобы подтвердить аккаунт.',
    checkSpamFolder: 'Если письма нет во входящих — проверьте папку Спам.',
    resendEmail: 'Отправить повторно',
    backToSignIn: 'Назад к входу',
    passwordMinLength: 'Пароль минимум 6 символов',
    waitingForVerification: 'Ожидаем подтверждения...',
    emailVerified: 'Email подтверждён!',
    emailVerifiedTitle: 'Вы подтверждены!',
    emailVerifiedMessage: 'Ваш email подтверждён. Добро пожаловать в 808!',
    redirecting: 'Перенаправляем...',
    
    // Upload validation
    audioFileRequired: 'Загрузите аудиофайл чтобы опубликовать бит',
    
    // Profile
    uploadedBeats: 'Загруженные биты',
    salesHistory: 'История продаж',
    totalSales: 'Всего продаж',
    revenue: 'Доход',
    totalPlays: 'Всего прослушиваний',
    followers: 'подписчиков',
    
    // Wallet
    wallet: 'Кошелёк',
    myWallet: 'Мой кошелёк',
    availableBalance: 'Доступный баланс',
    holdBalance: 'Заморожено',
    holdNote: 'Средства заморожены на 48 часов после продажи',
    pending: 'В ожидании',
    clearsIn: 'Зачисление через 7 дней',
    withdraw: 'Вывести',
    topUp: 'Пополнить',
    topUpBalance: 'Пополнить баланс',
    paymentMethods: 'Способы оплаты',
    addMethod: 'Добавить',
    transactionHistory: 'История транзакций',
    noTransactions: 'Нет транзакций',
    fundsReleased: 'Средства разморожены',
    connectWallet: 'Подключить кошелёк',
    cryptoComingSoon: 'Крипто (Скоро)',
    comingSoon: 'Скоро',
    paymentMethodsComingSoon: 'Способы пополнения и вывода скоро будут доступны',
    withdrawFunds: 'Вывод средств',
    amount: 'Сумма',
    available: 'Доступно',
    withdrawTo: 'Вывести на',
    cancel: 'Отмена',
    soldTo: 'Продано',
    withdrawal: 'Вывод',
    
    // Purchases
    myPurchases: 'Мои покупки',
    noPurchases: 'Нет покупок',
    startBuying: 'Покупайте биты у талантливых продюсеров',
    purchased: 'Куплено',
    license: 'Лицензия',
    downloadBeat: 'Скачать бит',
    download: 'Скачать',
    licenseOwned: 'Эта лицензия у вас есть',
    downloadNow: 'Скачать',
    onHold: 'Заморожено',
    completed: 'Завершено',
    cancelled: 'Отменено',
    disputed: 'Спор',
    pendingConfirmation: 'Ожидание подтверждения',
    sellerCheckingPayment: 'Продавец проверяет оплату...',
    noRefundTitle: 'Возврат не предусмотрен',
    noRefundDesc: 'Вы можете оспорить сделку. При наличии доказательств администратор может выдать бит вручную.',
    disputeButton: 'Оспорить',
    disputeUnderReview: 'Спор на рассмотрении',
    reportProblem: 'Сообщить о проблеме',
    describeIssue: 'Опишите проблему с этой покупкой',
    disputeReasonPlaceholder: 'Объясните что пошло не так...',
    submitDispute: 'Отправить спор',
    
    // Buy
    buyFor: 'Купить за',
    yourBalance: 'Ваш баланс',
    insufficientFunds: 'Недостаточно средств',
    needMore: 'Вам нужно ещё',
    toComplete: 'чтобы завершить покупку',
    topUpWallet: 'Пополнить баланс',
    purchaseSuccess: 'Покупка успешна!',
    beatNowYours: 'Бит теперь ваш. Можете скачать в любое время.',
    close: 'Закрыть',
    ownBeat: 'Это ваш бит',
    
    // Manual Purchase System
    contactToBuy: 'Связаться для покупки',
    directPayment: 'Прямая оплата продавцу • Ручная проверка',
    digitalGoodsNotice: 'Цифровой товар • Возврат невозможен после доставки',
    purchaseBeat: 'Покупка бита',
    review: 'Обзор',
    payment: 'Оплата',
    proof: 'Подтверждение',
    deliveryTime: 'Время доставки',
    deliveryTimeDesc: 'В течение 10 минут после подтверждения оплаты',
    manualVerification: 'Ручная проверка',
    manualVerificationDesc: 'Продавец проверяет оплату перед отправкой',
    noRefunds: 'Без возврата',
    noRefundsDesc: 'Цифровые товары не подлежат возврату после доставки',
    purchaseTerms: 'Условия покупки',
    term1: 'Оплата производится напрямую продавцу',
    term2: 'Платформа не обрабатывает и не хранит платежи',
    term3: 'Товар доставляется после подтверждения оплаты',
    term4: 'Все продажи окончательны из-за цифровой природы товара',
    continueToPayment: 'Продолжить к оплате',
    paymentInstructions: 'Инструкции по оплате',
    paymentInstructionsDesc: 'Отправьте оплату одним из способов ниже',
    amountToPay: 'Сумма к оплате',
    contactSeller: 'Связаться с продавцом',
    contactSellerDesc: 'Свяжитесь с продавцом напрямую для получения реквизитов',
    important: 'Важно',
    includeOrderRef: 'Укажите эту ссылку в сообщении об оплате:',
    iHavePaid: 'Я оплатил',
    submitPaymentProof: 'Отправить подтверждение',
    submitPaymentProofDesc: 'Загрузите скриншот подтверждения оплаты',
    uploadScreenshot: 'Нажмите чтобы загрузить скриншот',
    maxFileSize: 'Макс. размер файла: 10МБ',
    transactionId: 'ID транзакции / Номер',
    transactionIdPlaceholder: 'Введите ID транзакции или номер чека',
    yourEmail: 'Ваш Email',
    emailPlaceholder: 'Введите ваш email адрес',
    emailNote: 'Мы отправим бит на этот email после подтверждения',
    submitting: 'Отправка...',
    submitOrder: 'Отправить заказ',
    orderSubmitted: 'Заказ отправлен!',
    orderSubmittedDesc: 'Ваш заказ рассматривается продавцом',
    orderReference: 'Номер заказа',
    pendingVerification: 'Ожидает проверки',
    whatHappensNext: 'Что будет дальше?',
    nextStep1: 'Продавец проверит вашу оплату',
    nextStep2: 'После подтверждения вы получите бит на email',
    nextStep3: 'Доставка обычно занимает до 10 минут',
    checkEmail: 'Проверяйте почту для обновлений заказа',
    done: 'Готово',
    
    // Orders (Seller)
    orders: 'Заказы',
    incomingOrders: 'Входящие заказы',
    manageYourOrders: 'Управление заказами от покупателей',
    totalOrders: 'Всего',
    signInToViewOrders: 'Войдите чтобы увидеть ваши заказы',
    noOrders: 'Нет заказов',
    noOrdersDesc: 'У вас пока нет заказов',
    buyerInfo: 'Информация о покупателе',
    name: 'Имя',
    orderRef: 'Номер заказа',
    date: 'Дата',
    paymentProof: 'Подтверждение оплаты',
    viewFull: 'Посмотреть полностью',
    noProofUploaded: 'Подтверждение не загружено',
    approvePayment: 'Подтвердить оплату',
    rejectOrder: 'Отклонить',
    enterRejectReason: 'Введите причину отклонения:',
    readyToDeliver: 'Готово к доставке',
    sendBeatToEmail: 'Отправьте файл бита на email покупателя',
    sendEmail: 'Открыть почту',
    markDelivered: 'Отметить доставленным',
    rejectionReason: 'Причина отклонения',
    orderDelivered: 'Этот заказ был доставлен',
    approved: 'Подтверждён',
    rejected: 'Отклонён',
    delivered: 'Доставлен',
    status: 'Статус',
    
    // Seller Sales Tab
    pendingReview: 'Ожидает проверки',
    viewPaymentProof: 'Скрин оплаты',
    moneyReceived: 'Деньги пришли',
    moneyNotReceived: 'Деньги не пришли',
    dealCompleted: 'Сделка завершена',
    cancelledBuyerCanDispute: 'Отменено • Покупатель может открыть спор',
    
    // Dispute System
    disputeOrder: 'Спор',
    enterDisputeReason: 'Введите причину спора (объясните почему вы считаете оплату недействительной):',
    disputeSubmitted: 'Спор отправлен. Администратор рассмотрит это дело.',
    errorCreatingDispute: 'Не удалось создать спор',
    underAdminReview: 'На рассмотрении администратора',
    disputeReason: 'Причина спора',
    adminWillReview: 'Администратор рассмотрит дело и примет окончательное решение.',
    adminDeliveredOrder: 'Доставлено администратором',
    adminDeliveredDesc: 'Этот заказ был доставлен администратором после рассмотрения спора.',
    adminNotes: 'Заметки администратора',
    adminDelivered: 'Доставлено админом',
    paymentDate: 'Дата оплаты',
    paymentTime: 'Время оплаты',
    cardLastFour: 'Последние 4 цифры карты',
    cardLastFourPlaceholder: 'Последние 4 цифры вашей карты',
    actionHistory: 'История действий',
    
    // Admin Arbitration
    orderArbitration: 'Арбитраж заказов',
    sellerInfo: 'Информация о продавце',
    sellerId: 'ID продавца',
    beatId: 'ID бита',
    disputedBy: 'Спор открыт',
    adminActions: 'Действия администратора',
    forceDeliver: 'Принудительно доставить покупателю',
    approveOrder: 'Одобрить заказ',
    enterAdminNotes: 'Введите заметки администратора с объяснением вашего решения:',
    adminActionNote: 'Все действия администратора логируются и видны покупателю и продавцу.',
    
    // Purchase Modal - Admin Protection
    adminProtection: 'Защита администратора',
    adminProtectionDesc: 'Если продавец не доставит товар после действительной оплаты, администратор может принудительно доставить товар вам.',
    legalTitle: 'Важное юридическое уведомление',
    legal1: 'Эта платформа не обрабатывает, не хранит и не проводит платежи.',
    legal2: 'Все транзакции происходят напрямую между покупателем и продавцом.',
    legal3: 'Платформа только облегчает проверку подтверждений и доставку.',
    legal4: 'Продолжая, вы признаёте что это прямая P2P транзакция.',
    legal5: 'В случае споров администратор рассмотрит доказательства и примет окончательное решение.',
    
    // Stripe Wallet
    paymentSuccessful: 'Оплата прошла успешно! Ваш баланс обновлён.',
    paymentCanceled: 'Оплата была отменена.',
    paymentError: 'Не удалось обработать платёж. Попробуйте ещё раз.',
    selectAmount: 'Выберите сумму для пополнения кошелька',
    customAmount: 'Другая сумма',
    amountRange: 'Мин: $1 • Макс: $1,000',
    invalidAmount: 'Сумма должна быть от $5 до $1,000',
    creditDebitCard: 'Кредитная / Дебетовая карта',
    securePayment: 'Защищено Stripe. Мы не храним данные вашей карты.',
    payAmount: 'Оплатить',
    processing: 'Обработка...',
    failed: 'Ошибка',
    expired: 'Истекло',
    refund: 'Возврат',
    withdrawError: 'Не удалось вывести средства',
    
    // Sales
    sales: 'Продажи',
    salesCount: 'продаж',
    noSalesYet: 'Нет продаж',
    uploadBeatsToSell: 'Загружайте биты чтобы начать продавать',
    
    // Upload
    uploadBeatTitle: 'Загрузить бит',
    licenseFiles: 'Файлы лицензий',
    selectLicensesToSell: 'Выберите какие лицензии вы хотите продавать. Нажмите чекбокс для включения.',
    uploadFilesForEachLicense: 'Загрузите отдельные файлы для каждой лицензии',
    selectMp3: 'Выберите MP3 файл',
    selectWav: 'Выберите WAV файл',
    selectStems: 'Выберите стемы (ZIP)',
    selectExclusive: 'Выберите файл Exclusive',
    mp3FileRequired: 'MP3 файл обязателен',
    wavFileRequired: 'WAV файл обязателен (лицензия включена)',
    trackoutFileRequired: 'Trackout файл обязателен (лицензия включена)',
    exclusiveFileRequired: 'Exclusive файл обязателен (лицензия включена)',
    clickToEnable: 'Нажмите чтобы включить',
    onlyMp3Allowed: 'Только MP3 файлы',
    onlyWavAllowed: 'Только WAV файлы',
    onlyZipAllowed: 'Только ZIP/RAR файлы',
    onlyZipWavAllowed: 'Только ZIP, RAR или WAV файлы',
    uploadingMp3: 'Загрузка MP3...',
    uploadingWav: 'Загрузка WAV...',
    uploadingTrackout: 'Загрузка Trackout...',
    uploadingExclusive: 'Загрузка Exclusive...',
    audioFile: 'Аудио файл',
    dragDrop: 'Перетащите бит сюда или',
    browse: 'выберите файл',
    fileTypes: 'MP3, WAV, FLAC до 100МБ',
    uploadingAudio: 'Загрузка аудио...',
    uploadingCover: 'Загрузка обложки...',
    savingBeat: 'Сохранение бита...',
    coverImage: 'Обложка',
    addCover: 'Добавить обложку',
    optional: 'необязательно',
    coverLinkHint: 'Вставьте ссылку на обложку (imgur, imgbb и т.д.) - необязательно',
    titleRequired: 'Название обязательно',
    beatInfo: 'Информация о бите',
    title: 'Название',
    beatName: 'Название бита',
    selectGenre: 'Выберите жанр',
    selectKey: 'Выберите тональность',
    selectMood: 'Выберите настроение',
    pricing: 'Цены',
    publishBeat: 'Опубликовать',
    howToUpload: 'Как загрузить?',
    recommended: 'рекомендуется',
    driveStep1: 'Загрузите бит на Google Drive',
    driveStep2: 'Правый клик на файл → Поделиться',
    driveStep3: 'Установите доступ "Все у кого есть ссылка"',
    driveStep4: 'Скопируйте ссылку и вставьте сюда',
    dropboxStep1: 'Загрузите на Dropbox и получите ссылку',
    dropboxStep2: 'Вставьте ссылку сюда',
    willPlayOnSite: 'будет воспроизводиться на сайте',
    mayNotPlay: 'может не воспроизводиться, только ссылка',
    unknownPlatform: 'Неизвестная платформа',
    
    // Genres
    trap: 'Трэп',
    drill: 'Дрилл',
    rnb: 'R&B',
    hiphop: 'Хип-Хоп',
    pop: 'Поп',
    lofi: 'Лоу-Фай',
    
    // Moods
    dark: 'Тёмный',
    chill: 'Спокойный',
    aggressive: 'Агрессивный',
    energetic: 'Энергичный',
    sad: 'Грустный',
    happy: 'Весёлый',
    
    // Licenses
    mp3Lease: 'MP3 лицензия',
    wavLease: 'WAV лицензия',
    trackout: 'Trackout',
    exclusive: 'Эксклюзив',

    // Country selector
    selectCountry: 'Выбрать страну',

    // Settings
    settings: 'Настройки',
    clickToChangeAvatar: 'Нажмите чтобы изменить аватар',
    canChangeNameIn: 'Вы можете изменить имя через',
    days: 'дней',
    saveChanges: 'Сохранить',
    settingsSaved: 'Настройки сохранены',
    dangerZone: 'Опасная зона',
    
    // Profile
    myBeats: 'Мои биты',
    liked: 'Понравившиеся',
    purchases: 'Покупки',
    noBeatsYet: 'Пока нет битов',
    uploadFirstBeat: 'Загрузите свой первый бит чтобы начать продавать',
    noLikedBeats: 'Нет понравившихся битов',
    exploreLikeBeats: 'Исследуйте биты и добавляйте в избранное',
    exploreToBuy: 'Исследуйте биты и покупайте понравившиеся',
    from: 'от',
    exploreCatalog: 'Смотреть каталог',
    editBeat: 'Редактировать бит',
    delete: 'Удалить',
    deleteBeatConfirm: 'Удалить этот бит?',
    deleteBeatWarning: 'Это действие нельзя отменить. Бит будет удалён навсегда.',

    // Terms page
    termsTitle: '808 — Условия использования',
    privacyTitle: 'Политика конфиденциальности',
    licensingTitle: 'Лицензионное соглашение',
    effectiveDate: 'Дата вступления в силу: 27 января 2026',
    termsIntro: 'Настоящие Условия использования («Условия») регулируют ваш доступ к платформе 808 («808», «мы», «нас») и её использование.',
    termsAgreeIntro: 'Создавая аккаунт или используя платформу, вы соглашаетесь с этими Условиями.',
    
    eligibilityTitle: '1. Право на использование',
    eligibilityText: 'Вам должно быть не менее 18 лет для использования 808. Используя платформу, вы подтверждаете соответствие этому требованию.',
    
    accountsTitle: '2. Аккаунты',
    accountsSecurity: 'Вы несёте ответственность за безопасность своего аккаунта',
    accountsActivity: 'Вся активность под вашим аккаунтом — ваша ответственность',
    accountsAccurate: 'Вы должны предоставлять точную и актуальную информацию',
    
    platformTitle: '3. Описание платформы',
    platformText: '808 — это глобальный цифровой маркетплейс, позволяющий продюсерам загружать, лицензировать и продавать музыкальные биты, а покупателям — приобретать лицензии на эти биты.',
    
    ownershipTitle: '4. Права на контент',
    ownershipRetain: 'Продюсеры сохраняют полное право собственности на загруженные биты',
    ownershipConfirm: 'Загружая контент, вы подтверждаете наличие всех необходимых прав',
    ownershipNoClaim: '808 не претендует на право собственности на пользовательский контент',
    ownershipGrant: 'Вы предоставляете 808 неисключительную, всемирную, безвозмездную лицензию на размещение, трансляцию, отображение и продвижение вашего контента исключительно для работы платформы',
    
    copyrightTitle: '5. Авторские права и DMCA',
    copyrightRespect: '808 уважает права интеллектуальной собственности.',
    copyrightNotice: 'Если вы считаете, что материал, защищённый авторским правом, был загружен без разрешения, отправьте уведомление DMCA на',
    copyrightViolation: 'Повторные нарушения авторских прав могут привести к блокировке аккаунта.',
    
    licensesTitle: '6. Лицензии и покупки',
    licensesGrant: 'Покупка бита предоставляет лицензию, а не право собственности',
    licensesDefined: 'Условия лицензии определены на странице каждого бита',
    licensesBinding: 'Лицензии являются обязательными после покупки',
    licensesFinal: 'Все продажи окончательны, если иное не требуется законом',
    
    paymentsTitle: '7. Платежи и комиссии',
    paymentsProcessed: 'Платежи обрабатываются сторонними провайдерами (например, Stripe, PayPal)',
    paymentsFee: '808 может взимать комиссию за услуги платформы',
    paymentsTax: 'Вы несёте ответственность за все применимые налоги',
    paymentsErrors: '808 не несёт ответственности за ошибки или задержки платёжных провайдеров',
    
    prohibitedTitle: '8. Запрещённое использование',
    prohibitedIntro: 'Вы не можете:',
    prohibitedStolen: 'Загружать украденный или нарушающий права контент',
    prohibitedIllegal: 'Использовать платформу для незаконной деятельности',
    prohibitedExploit: 'Пытаться эксплуатировать, реверс-инжинирить или наносить вред платформе',
    
    terminationTitle: '9. Прекращение доступа',
    terminationText: '808 оставляет за собой право приостановить или заблокировать аккаунты, нарушающие эти Условия или применимое законодательство.',
    
    disclaimerTitle: '10. Отказ от ответственности',
    disclaimerText: 'Платформа предоставляется «как есть» без каких-либо гарантий. 808 не предоставляет юридических консультаций и не несёт ответственности за споры между покупателями и продавцами.',
    
    liabilityTitle: '11. Ограничение ответственности',
    liabilityText: 'В максимальной степени, разрешённой законом, 808 не несёт ответственности за косвенные, случайные или последующие убытки, включая упущенную выгоду или потерю данных.',
    
    governingTitle: '12. Применимое право',
    governingText: 'Эти Условия регулируются и толкуются в соответствии с применимым международным законодательством.',
    
    changesTitle: '13. Изменения',
    changesText: 'Мы можем обновить эти Условия в любое время. Продолжение использования платформы означает принятие обновлённых Условий.',
    
    // Privacy
    dataCollectTitle: '1. Какие данные мы собираем',
    dataAccount: 'Информация об аккаунте (email, имя пользователя)',
    dataPayment: 'Платёжные данные (обрабатываются третьими сторонами)',
    dataUsage: 'Данные об использовании и аналитика',
    
    dataUseTitle: '2. Как мы используем данные',
    dataOperate: 'Для работы и улучшения платформы',
    dataProcess: 'Для обработки транзакций',
    dataCommunicate: 'Для отправки важных уведомлений',
    
    dataSharingTitle: '3. Передача данных',
    dataSharingText: 'Мы не продаём персональные данные. Данные передаются только доверенным поставщикам услуг при необходимости.',
    
    legalComplianceTitle: '4. Соответствие законодательству',
    legalComplianceText: 'Мы обрабатываем персональные данные в соответствии с применимым законодательством о защите данных, включая GDPR и CCPA.',
    
    securityTitle: '5. Безопасность',
    securityText: 'Мы применяем стандартные отраслевые меры безопасности для защиты вашей информации.',
    
    yourRightsTitle: '6. Ваши права',
    yourRightsText: 'Вы можете запросить доступ, исправление или удаление ваших персональных данных в любое время, связавшись с',
    
    // Licensing
    licensingIntro: 'Данное Лицензионное соглашение применяется ко всем покупкам битов на 808.',
    
    licenseGrantTitle: '1. Предоставление лицензии',
    licenseGrantText: 'При покупке покупатель получает неисключительную или исключительную лицензию, как указано на странице бита.',
    
    restrictionsTitle: '2. Ограничения',
    restrictionsIntro: 'Если явно не указано иное, покупатель не может:',
    restrictionsClaim: 'Заявлять право собственности на бит',
    restrictionsResell: 'Перепродавать или сублицензировать бит',
    restrictionsRegister: 'Регистрировать бит как свой в агентствах авторского права',
    
    creditTitle: '3. Указание авторства',
    creditText: 'Если это требуется лицензией, необходимо указать имя продюсера.',
    
    licenseTerminationTitle: '4. Прекращение действия',
    licenseTerminationText: 'Нарушение условий лицензии может привести к её отзыву без возврата средств.',
    
    agreementNotice: 'Создавая аккаунт, вы соглашаетесь с Условиями использования, Политикой конфиденциальности и Лицензионным соглашением 808.',
  },
  
  uk: {
    // Header
    signIn: 'Увійти',
    signOut: 'Вийти',
    signInRequired: 'Потрібен вхід',
    signInToAccessWallet: 'Увійдіть, щоб отримати доступ до гаманця',
    
    // Home
    tagline: 'Глобальний маркетплейс бітів',
    exploreBeats: 'Переглянути біти',
    uploadBeat: 'Завантажити біт',
    buyBeat: 'Купити біт',
    sellBeat: 'Продати біт',
    
    // Explore
    explore: 'Каталог',
    beats: 'бітів',
    searchPlaceholder: 'Пошук бітів або продюсерів...',
    genre: 'Жанр',
    mood: 'Настрій',
    bpm: 'BPM',
    price: 'Ціна',
    all: 'Усі',
    noBeatsFound: 'Біти не знайдені',
    buy: 'Купити',
    
    // Beat Page
    back: 'Назад',
    selectLicense: 'Оберіть ліцензію',
    secureCheckout: 'Безпечна оплата • Миттєве завантаження',
    plays: 'прослуховувань',
    by: 'від',
    
    // Auth
    welcomeBack: 'З поверненням',
    signInToAccount: 'Увійдіть в акаунт',
    createAccount: 'Створити акаунт',
    startSelling: 'Почніть продавати біти по всьому світу',
    email: 'Email',
    password: 'Пароль',
    producerName: "Ім'я продюсера",
    forgotPassword: 'Забули пароль?',
    dontHaveAccount: 'Немає акаунту?',
    alreadyHaveAccount: 'Вже є акаунт?',
    signUp: 'Реєстрація',
    resetPassword: 'Скидання пароля',
    enterEmailReset: 'Введіть email для отримання посилання',
    sendResetLink: 'Надіслати посилання',
    continueWithGoogle: 'Продовжити з Google',
    termsAgree: 'Створюючи акаунт, ви погоджуєтесь з',
    termsOfService: 'Умовами використання',
    and: 'та',
    privacyPolicy: 'Політикою конфіденційності',
    or: 'або',
    
    // Email verification
    verifyEmailFirst: 'Спочатку підтвердіть email. Перевірте пошту.',
    verificationSent: 'Лист надіслано! Перевірте пошту.',
    verificationResent: 'Лист надіслано повторно!',
    checkYourEmail: 'Перевірте пошту',
    verificationSentTo: 'Ми надіслали посилання на',
    clickLinkToVerify: 'Натисніть на посилання в листі щоб підтвердити акаунт.',
    checkSpamFolder: 'Якщо листа немає у вхідних — перевірте папку Спам.',
    resendEmail: 'Надіслати повторно',
    backToSignIn: 'Назад до входу',
    passwordMinLength: 'Пароль мінімум 6 символів',
    waitingForVerification: 'Очікуємо підтвердження...',
    emailVerified: 'Email підтверджено!',
    emailVerifiedTitle: 'Ви підтверджені!',
    emailVerifiedMessage: 'Ваш email підтверджено. Ласкаво просимо до 808!',
    redirecting: 'Перенаправляємо...',
    audioFileRequired: 'Завантажте аудіофайл щоб опублікувати біт',
    
    // Profile
    uploadedBeats: 'Завантажені біти',
    salesHistory: 'Історія продажів',
    totalSales: 'Всього продажів',
    revenue: 'Дохід',
    totalPlays: 'Всього прослуховувань',
    followers: 'підписників',
    
    // Wallet
    wallet: 'Гаманець',
    myWallet: 'Мій гаманець',
    availableBalance: 'Доступний баланс',
    holdBalance: 'Заморожено',
    holdNote: 'Кошти заморожені на 48 годин після продажу',
    pending: 'В очікуванні',
    clearsIn: 'Зарахування через 7 днів',
    withdraw: 'Вивести',
    topUp: 'Поповнити',
    topUpBalance: 'Поповнити баланс',
    paymentMethods: 'Способи оплати',
    addMethod: 'Додати',
    transactionHistory: 'Історія транзакцій',
    noTransactions: 'Немає транзакцій',
    fundsReleased: 'Кошти розморожені',
    connectWallet: 'Підключити гаманець',
    cryptoComingSoon: 'Крипто (Скоро)',
    comingSoon: 'Скоро',
    paymentMethodsComingSoon: 'Способи поповнення та виведення скоро будуть доступні',
    withdrawFunds: 'Виведення коштів',
    amount: 'Сума',
    available: 'Доступно',
    withdrawTo: 'Вивести на',
    cancel: 'Скасувати',
    soldTo: 'Продано',
    withdrawal: 'Виведення',
    
    // Purchases
    myPurchases: 'Мої покупки',
    noPurchases: 'Немає покупок',
    startBuying: 'Купуйте біти у талановитих продюсерів',
    purchased: 'Куплено',
    license: 'Ліцензія',
    downloadBeat: 'Завантажити біт',
    download: 'Завантажити',
    licenseOwned: 'Ця ліцензія у вас є',
    downloadNow: 'Завантажити',
    onHold: 'Заморожено',
    completed: 'Завершено',
    cancelled: 'Скасовано',
    disputed: 'Спір',
    pendingConfirmation: 'Очікування підтвердження',
    sellerCheckingPayment: 'Продавець перевіряє оплату...',
    noRefundTitle: 'Повернення не передбачено',
    noRefundDesc: 'Ви можете оскаржити угоду. При наявності доказів адміністратор може видати біт вручну.',
    disputeButton: 'Оскаржити',
    disputeUnderReview: 'Спір на розгляді',
    reportProblem: 'Повідомити про проблему',
    describeIssue: 'Опишіть проблему з цією покупкою',
    disputeReasonPlaceholder: 'Поясніть що пішло не так...',
    submitDispute: 'Надіслати спір',
    
    // Buy
    buyFor: 'Купити за',
    yourBalance: 'Ваш баланс',
    insufficientFunds: 'Недостатньо коштів',
    needMore: 'Вам потрібно ще',
    toComplete: 'щоб завершити покупку',
    topUpWallet: 'Поповнити баланс',
    purchaseSuccess: 'Покупка успішна!',
    beatNowYours: 'Біт тепер ваш. Можете завантажити в будь-який час.',
    close: 'Закрити',
    ownBeat: 'Це ваш біт',
    
    // Manual Purchase System
    contactToBuy: "Зв'язатися для покупки",
    directPayment: 'Пряма оплата продавцю • Ручна перевірка',
    digitalGoodsNotice: 'Цифровий товар • Повернення неможливе після доставки',
    purchaseBeat: 'Покупка біту',
    review: 'Огляд',
    payment: 'Оплата',
    proof: 'Підтвердження',
    deliveryTime: 'Час доставки',
    deliveryTimeDesc: 'Протягом 10 хвилин після підтвердження оплати',
    manualVerification: 'Ручна перевірка',
    manualVerificationDesc: 'Продавець перевіряє оплату перед відправкою',
    noRefunds: 'Без повернення',
    noRefundsDesc: 'Цифрові товари не підлягають поверненню після доставки',
    purchaseTerms: 'Умови покупки',
    term1: 'Оплата здійснюється напряму продавцю',
    term2: 'Платформа не обробляє і не зберігає платежі',
    term3: 'Товар доставляється після підтвердження оплати',
    term4: 'Усі продажі остаточні через цифрову природу товару',
    continueToPayment: 'Продовжити до оплати',
    paymentInstructions: 'Інструкції з оплати',
    paymentInstructionsDesc: 'Надішліть оплату одним із способів нижче',
    amountToPay: 'Сума до оплати',
    contactSeller: "Зв'язатися з продавцем",
    contactSellerDesc: "Зв'яжіться з продавцем напряму для отримання реквізитів",
    important: 'Важливо',
    includeOrderRef: 'Вкажіть це посилання в повідомленні про оплату:',
    iHavePaid: 'Я оплатив',
    submitPaymentProof: 'Надіслати підтвердження',
    submitPaymentProofDesc: 'Завантажте скріншот підтвердження оплати',
    uploadScreenshot: 'Натисніть щоб завантажити скріншот',
    maxFileSize: 'Макс. розмір файлу: 10МБ',
    transactionId: 'ID транзакції / Номер',
    transactionIdPlaceholder: 'Введіть ID транзакції або номер чеку',
    yourEmail: 'Ваш Email',
    emailPlaceholder: 'Введіть вашу email адресу',
    emailNote: 'Ми надішлемо біт на цей email після підтвердження',
    submitting: 'Надсилання...',
    submitOrder: 'Надіслати замовлення',
    orderSubmitted: 'Замовлення надіслано!',
    orderSubmittedDesc: 'Ваше замовлення розглядається продавцем',
    orderReference: 'Номер замовлення',
    pendingVerification: 'Очікує перевірки',
    whatHappensNext: 'Що буде далі?',
    nextStep1: 'Продавець перевірить вашу оплату',
    nextStep2: 'Після підтвердження ви отримаєте біт на email',
    nextStep3: 'Доставка зазвичай займає до 10 хвилин',
    checkEmail: 'Перевіряйте пошту для оновлень замовлення',
    done: 'Готово',
    
    // Orders (Seller)
    orders: 'Замовлення',
    incomingOrders: 'Вхідні замовлення',
    manageYourOrders: 'Управління замовленнями від покупців',
    totalOrders: 'Всього',
    signInToViewOrders: 'Увійдіть щоб побачити ваші замовлення',
    noOrders: 'Немає замовлень',
    noOrdersDesc: 'У вас поки немає замовлень',
    buyerInfo: 'Інформація про покупця',
    name: "Ім'я",
    orderRef: 'Номер замовлення',
    date: 'Дата',
    paymentProof: 'Підтвердження оплати',
    viewFull: 'Переглянути повністю',
    noProofUploaded: 'Підтвердження не завантажено',
    approvePayment: 'Підтвердити оплату',
    rejectOrder: 'Відхилити',
    enterRejectReason: 'Введіть причину відхилення:',
    readyToDeliver: 'Готово до доставки',
    sendBeatToEmail: 'Надішліть файл біту на email покупця',
    sendEmail: 'Відкрити Email',
    markDelivered: 'Позначити доставленим',
    rejectionReason: 'Причина відхилення',
    orderDelivered: 'Це замовлення було доставлено',
    approved: 'Підтверджено',
    rejected: 'Відхилено',
    delivered: 'Доставлено',
    status: 'Статус',
    
    // Seller Sales Tab
    pendingReview: 'Очікує перевірки',
    viewPaymentProof: 'Скрін оплати',
    moneyReceived: 'Гроші надійшли',
    moneyNotReceived: 'Гроші не надійшли',
    dealCompleted: 'Угода завершена',
    cancelledBuyerCanDispute: 'Скасовано • Покупець може відкрити спір',
    
    // Dispute System
    disputeOrder: 'Спір',
    enterDisputeReason: 'Введіть причину спору (поясніть чому ви вважаєте оплату недійсною):',
    disputeSubmitted: 'Спір надіслано. Адміністратор розгляне цю справу.',
    errorCreatingDispute: 'Не вдалося створити спір',
    underAdminReview: 'На розгляді адміністратора',
    disputeReason: 'Причина спору',
    adminWillReview: 'Адміністратор розгляне справу і прийме остаточне рішення.',
    adminDeliveredOrder: 'Доставлено адміністратором',
    adminDeliveredDesc: 'Це замовлення було доставлено адміністратором після розгляду спору.',
    adminNotes: 'Нотатки адміністратора',
    adminDelivered: 'Доставлено адміном',
    paymentDate: 'Дата оплати',
    paymentTime: 'Час оплати',
    cardLastFour: 'Останні 4 цифри картки',
    cardLastFourPlaceholder: 'Останні 4 цифри вашої картки',
    actionHistory: 'Історія дій',
    
    // Profile tabs
    myBeats: 'Мої біти',
    sales: 'Продажі',
    salesCount: 'продажів',
    liked: 'Вподобані',
    purchases: 'Покупки',
    noBeatsYet: 'Поки немає бітів',
    uploadFirstBeat: 'Завантажте ваш перший біт щоб почати продавати',
    noLikedBeats: 'Немає вподобаних бітів',
    exploreLikeBeats: 'Переглядайте біти та вподобайте улюблені',
    exploreToBuy: 'Переглядайте біти та купуйте улюблені',
    from: 'від',
    exploreCatalog: 'Переглянути каталог',
    noSalesYet: 'Поки немає продажів',
    uploadBeatsToSell: 'Завантажте біти щоб почати продавати',
    
    // Settings
    settings: 'Налаштування',
    clickToChangeAvatar: 'Натисніть щоб змінити аватар',
    canChangeNameIn: 'Ви можете змінити ім\'я через',
    days: 'днів',
    saveChanges: 'Зберегти зміни',
    settingsSaved: 'Налаштування збережено',
    dangerZone: 'Небезпечна зона',
    selectCountry: 'Обрати мову',
    
    // Upload
    uploadBeatTitle: 'Завантажити біт',
    licenseFiles: 'Файли ліцензій',
    selectLicensesToSell: 'Оберіть які ліцензії ви хочете продавати.',
    uploadFilesForEachLicense: 'Завантажте окремі файли для кожного типу ліцензії',
    selectMp3: 'Обрати MP3 файл',
    selectWav: 'Обрати WAV файл',
    selectStems: 'Обрати Stems (ZIP)',
    selectExclusive: 'Обрати Exclusive файл',
    mp3FileRequired: 'MP3 файл обов\'язковий',
    wavFileRequired: 'WAV файл обов\'язковий (ліцензія увімкнена)',
    trackoutFileRequired: 'Trackout файл обов\'язковий (ліцензія увімкнена)',
    exclusiveFileRequired: 'Exclusive файл обов\'язковий (ліцензія увімкнена)',
    clickToEnable: 'Натисніть щоб увімкнути',
    onlyMp3Allowed: 'Тільки MP3 файли дозволені',
    onlyWavAllowed: 'Тільки WAV файли дозволені',
    onlyZipAllowed: 'Тільки ZIP/RAR файли дозволені',
    onlyZipWavAllowed: 'Тільки ZIP, RAR або WAV файли дозволені',
    uploadingMp3: 'Завантаження MP3...',
    uploadingWav: 'Завантаження WAV...',
    uploadingTrackout: 'Завантаження Trackout...',
    uploadingExclusive: 'Завантаження Exclusive...',
    audioFile: 'Аудіо файл',
    dragDrop: 'Перетягніть ваш біт сюди, або',
    browse: 'виберіть',
    fileTypes: 'MP3, WAV, FLAC до 100MB',
    uploadingAudio: 'Завантаження аудіо...',
    uploadingCover: 'Завантаження обкладинки...',
    savingBeat: 'Збереження біту...',
    coverImage: 'Обкладинка',
    addCover: 'Додати обкладинку',
    optional: 'необов\'язково',
    coverLinkHint: 'Вставте посилання на обкладинку (imgur, imgbb, тощо) - необов\'язково',
    titleRequired: 'Назва обов\'язкова',
    beatInfo: 'Інформація про біт',
    title: 'Назва',
    beatName: 'Назва біту',
    selectGenre: 'Обрати жанр',
    selectKey: 'Обрати тональність',
    selectMood: 'Обрати настрій',
    pricing: 'Ціни',
    publishBeat: 'Опублікувати біт',
    howToUpload: 'Як завантажити?',
    recommended: 'рекомендовано',
    driveStep1: 'Завантажте ваш біт на Google Drive',
    driveStep2: 'Клацніть правою кнопкою → Поділитися',
    driveStep3: 'Встановіть доступ "Усім, хто має посилання"',
    driveStep4: 'Скопіюйте посилання і вставте сюди',
    dropboxStep1: 'Завантажте на Dropbox і отримайте посилання для поширення',
    dropboxStep2: 'Вставте посилання сюди',
    willPlayOnSite: 'буде відтворюватися прямо на сайті',
    mayNotPlay: 'може не відтворюватися напряму, тільки посилання',
    unknownPlatform: 'Невідома платформа',
    
    // Genres/Moods
    trap: 'Trap',
    drill: 'Drill',
    rnb: 'R&B',
    hiphop: 'Hip-Hop',
    pop: 'Pop',
    lofi: 'Lo-Fi',
    dark: 'Темний',
    chill: 'Спокійний',
    aggressive: 'Агресивний',
    energetic: 'Енергійний',
    sad: 'Сумний',
    happy: 'Веселий',
    
    // License types
    mp3Lease: 'MP3 Ліцензія',
    wavLease: 'WAV Ліцензія',
    trackout: 'Trackout',
    exclusive: 'Ексклюзив',
  },
}

// Fallback to English for missing translations
const getTranslation = (lang, key) => {
  return translations[lang]?.[key] || translations.en[key] || key
}

export function LanguageProvider({ children }) {
  const [country, setCountry] = useState(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('country')
      return saved ? JSON.parse(saved) : countries[0]
    }
    return countries[0]
  })

  useEffect(() => {
    localStorage.setItem('country', JSON.stringify(country))
    document.documentElement.lang = country.lang
  }, [country])

  const t = (key) => getTranslation(country.lang, key)

  const changeCountry = (countryCode) => {
    const newCountry = countries.find(c => c.code === countryCode)
    if (newCountry) {
      setCountry(newCountry)
    }
  }

  return (
    <LanguageContext.Provider value={{ country, countries, changeCountry, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
